### ISSUE TITLE
As a user I want to see meaningful error messages and have a pretty UI in order to have a smooth and comfortable experience playing the game

### ISSUE THREAD

**Issue by mirjamweibel** [sopra-fs24-group-20/sopra-fs24-group-20-client#86]
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#85
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#84
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#87
- [x] sopra-fs24-group-20/sopra-fs24-group-20-client#89
- [x] #95 
- [x] #125 
- [x] #126
